name: "tagged-release"

on:
  push:
    tags:
      - 'v*'
      - '!*-rc*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v1

      - name: install doc deps
        run: sudo apt-get install --yes doxygen graphviz latexmk texlive-latex-extra

      - name: install platform io
        run: | 
          pip3 install -U setuptools
          pip3 install -U wheel
          pip3 install -U platformio
          python3 -m platformio update
          python3 -m platformio lib -g install "adafruit/DHT sensor library"
          python3 -m platformio lib -g install "adafruit/Adafruit Unified Sensor"

      - name: building examples and running the unit tests
        run: bash ./.scripts/ci_local.sh

      - name: prepare for building docs
        run: |
          mkdir doc/html
          mkdir doc/latex
      
      - name: build documentation
        run: bash .scripts/doxygen_multilang.sh

      - name: Check code meets quality standards
        id: codiga
        uses: codiga/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
          min_quality_grade: 'EXCELLENT'
          min_quality_score: '99'
          max_defects_rate: '0.01'
          max_complex_functions_rate: '0.01'
          max_long_functions_rate: '0.01'
          project_name: 'LedController'
          max_timeout_sec: '600'

      - name: pack repo
        run: |
          zip -r release.zip License README.md library.properties keywords.txt .vscode examples

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            License
            release.zip
            refman_english.pdf
            refman_german.pdf

      - name: Deploy to pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: doc/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build-artifact-${{ matrix.os }}-${{ matrix.compiler }}
          path: .
